# Application configuration

app:
  name: "Professional Iris Classifier"
  version: "1.0.0"
  assets_path: "assets"
  debug: false

model:
  path: "models/iris_model.pkl"
  version: "1.0.0"
  update_frequency: "monthly"

features:
  min_values:
    sepal length (cm): 4.0
    sepal width (cm): 2.0
    petal length (cm): 1.0
    petal width (cm): 0.1
  max_values:
    sepal length (cm): 8.0
    sepal width (cm): 4.5
    petal length (cm): 7.0
    petal width (cm): 2.5
  default_values:
    sepal length (cm): 5.5
    sepal width (cm): 3.0
    petal length (cm): 4.0
    petal width (cm): 1.0
  descriptions:
    sepal length (cm): "Length of the sepal in centimeters"
    sepal width (cm): "Width of the sepal in centimeters"
    petal length (cm): "Length of the petal in centimeters"
    petal width (cm): "Width of the petal in centimeters"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log" 